const INITIAL_REQUEST_WAS_SENT = 'INITIAL_REQUEST_WAS_SENT';
const SEARCH_ID_WAS_RECIEVED = 'SEARCH_ID_WAS_RECIEVED';
const RESULTS_REQUEST_WAS_SENT = 'RESULTS_REQUEST_WAS_SENT';
const RESULTS_WAS_RECIEVED = 'RESULTS_WAS_RECIEVED';

export {
    INITIAL_REQUEST_WAS_SENT,
    SEARCH_ID_WAS_RECIEVED,
    RESULTS_REQUEST_WAS_SENT,
    RESULTS_WAS_RECIEVED
}