export const INITIAL_REQUEST_DID_SEND = 'INITIAL_REQUEST_DID_SEND';
export const INITIAL_RESPONSE_WAS_RECIEVED = 'INITIAL_RESPONSE_WAS_RECIEVED';
export const RESULT_REQUEST_DID_SEND = 'RESULT_REQUEST_DID_SEND';
export const RESULT_RESPONSE_WAS_RECIEVED = 'RESULT_RESPONSE_WAS_RECIEVED';
export const SEARCH_FINISHED = 'SEARCH_FINISHED';
export const RERENDER_DISPLAYED_TICKETS = 'RERENDER_DISPLAYED_TICKETS';
export const REFRESH_SEARCH_STATE = 'REFRESH_SEARCH_STATE';