export const CHEAPEST_SORT_WAS_CLICKED = 'CHEAPEST_SORT_WAS_CLICKED';
export const FASTEST_SORT_WAS_CLICKED = 'FASTEST_SORT_WAS_CLICKED';
export const OPTIMAL_SORT_WAS_CLICKED = 'OPTIMAL_SORT_WAS_CLICKED';
export const CHEAPEST = 'CHEAPEST'
export const FASTEST = 'FASTEST'
export const OPTIMAL = 'OPTIMAL'
export const REFRESH_SORT_STATE = 'REFRESH_SORT_STATE'